def ContentType(content_type):
    Type, Subtype = content_type.split('/')
    return Type, Subtype
"""
Following comments are of no use. But I spend an hour typing these.
So I won't delete them.
Content Type of HTTP responce are shown as follows:
    extension-name  content-type(type/subtype)
    .*	            application/octet-stream
    .001	        application/x-001
    .323	        text/h323
    .907	        drawing/907
    .acp	        audio/x-mei-aac
    .aif	        audio/aiff
    .aiff	        audio/aiff
    .asa	        text/asa
    .asp	        text/asp
    .au	            audio/basic
    .awf	        application/vnd.adobe.workflow
    .bmp	        application/x-bmp
    .c4t	        application/x-c4t
    .cal	        application/x-cals
    .cdf	        application/x-netcdf
    .cel	        application/x-cel
    .cg4	        application/x-g4
    .cit	        application/x-cit
    .cml	        text/xml
    .cmx	        application/x-cmx
    .crl	        application/pkix-crl
    .csi	        application/x-csi
    .cut	        application/x-cut
    .dbm	        application/x-dbm
    .dcd	        text/xml
    .der	        application/x-x509-ca-cert
    .dib	        application/x-dib
    .doc	        application/msword
    .drw	        application/x-drw
    .dwf	        Model/vnd.dwf
    .dwg	        application/x-dwg
    .dxf	        application/x-dxf
    .emf	        application/x-emf
    .ent	        text/xml
    .eps	        application/x-ps
    .etd	        application/x-ebx
    .fax	        image/fax
    .fif	        application/fractals
    .frm	        application/x-frm
    .gbr	        application/x-gbr
    .gif	        image/gif
    .gp4	        application/x-gp4
    .hmr	        application/x-hmr
    .hpl	        application/x-hpl
    .hrf	        application/x-hrf
    .htc	        text/x-component
    .html	        text/html
    .htx	        text/html
    .ico	        image/x-icon
    .iff	        application/x-iff
    .igs	        application/x-igs
    .img	        application/x-img
    .isp	        application/x-internet-signup
    .java	        java/*
    .jpe	        image/jpeg
    .jpeg	        image/jpeg
    .jpg	        application/x-jpg
    .jsp	        text/html
    .lar	        application/x-laplayer-reg
    .lavs	        audio/x-liquid-secure
    .lmsff	        audio/x-la-lms
    .ltr	        application/x-ltr
    .m2v	        video/x-mpeg
    .m4e	        video/mpeg4
    .man	        application/x-troff-man
    .mdb	        application/msaccess
    .mfp	        application/x-shockwave-flash
    .mhtml	        message/rfc822
    .mid	        audio/mid
    .mil	        application/x-mil
    .mnd	        audio/x-musicnet-download
    .mocha	        application/x-javascript
    .mp1	        audio/mp1
    .mp2v	        video/mpeg
    .mp4	        video/mpeg4
    .mpd	        application/vnd.ms-project
    .mpeg	        video/mpg
    .mpga	        audio/rn-mpeg
    .mps	        video/x-mpeg
    .mpv	        video/mpg
    .mpw	        application/vnd.ms-project
    .mtx	        text/xml
    .net	        image/pnetvue
    .nws	        message/rfc822
    .out	        application/x-out
    .p12	        application/x-pkcs12
    .p7c	        application/pkcs7-mime
    .p7r	        application/x-pkcs7-certreqresp
    .pc5	        application/x-pc5
    .pcl	        application/x-pcl
    .pdf	        application/pdf
    .pdx	        application/vnd.adobe.pdx
    .pgl	        application/x-pgl
    .pko	        application/vnd.ms-pki.pko
    .plg	        text/html
    .plt	        application/x-plt
    .png	        application/x-png
    .ppa	        application/vnd.ms-powerpoint
    .pps	        application/vnd.ms-powerpoint
    .ppt	        application/x-ppt
    .prf	        application/pics-rules
    .prt	        application/x-prt
    .ps	            application/postscript
    .pwz	        application/vnd.ms-powerpoint
    .ra	audi        o/vnd.rn-realaudio
    .ras	        application/x-ras
    .rdf	        text/xml
    .red	        application/x-red
    .rjs	        application/vnd.rn-realsystem-rjs
    .rlc	        application/x-rlc
    .rm	            application/vnd.rn-realmedia
    .rmi	        audio/mid
    .rmm	        audio/x-pn-realaudio
    .rms	        application/vnd.rn-realmedia-secure
    .rmx	        application/vnd.rn-realsystem-rmx
    .rp	            image/vnd.rn-realpix
    .rsml	        application/vnd.rn-rsml
    .rtf	        application/msword
    .rv	            video/vnd.rn-realvideo
    .sat	        application/x-sat
    .sdw	        application/x-sdw
    .slb	        application/x-slb
    .slk	        drawing/x-slk
    .smil	        application/smil
    .snd	        audio/basic
    .sor	        text/plain
    .spl	        application/futuresplash
    .ssm	        application/streamingmedia
    .stl	        application/vnd.ms-pki.stl
    .sty	        application/x-sty
    .swf	        application/x-shockwave-flash
    .tg4	        application/x-tg4
    .tif	        image/tiff
    .tiff	        image/tiff
    .top	        drawing/x-top
    .tsd	        text/xml
    .uin	        application/x-icq
    .vcf	        text/x-vcard
    .vdx	        application/vnd.visio
    .vpg	        application/x-vpeg005
    .vsd	        application/x-vsd
    .vst	        application/vnd.visio
    .vsw	        application/vnd.visio
    .vtx	        application/vnd.visio
    .wav	        audio/wav
    .wb1	        application/x-wb1
    .wb3	        application/x-wb3
    .wiz	        application/msword
    .wk4	        application/x-wk4
    .wks	        application/x-wks
    .wma	        audio/x-ms-wma
    .wmf	        application/x-wmf
    .wmv	        video/x-ms-wmv
    .wmz	        application/x-ms-wmz
    .wpd	        application/x-wpd
    .wpl	        application/vnd.ms-wpl
    .wr1	        application/x-wr1
    .wrk	        application/x-wrk
    .ws2	        application/x-ws
    .wsdl	        text/xml
    .xdp	        application/vnd.adobe.xdp
    .xfd	        application/vnd.adobe.xfd
    .xhtml	        text/html
    .xls	        application/x-xls
    .xml	        text/xml
    .xq	            text/xml
    .xquery	        text/xml
    .xsl	        text/xml
    .xwd	        application/x-xwd
    .sis	        application/vnd.symbian.install
    .x_t	        application/x-x_t
    .apk	        application/vnd.android.package-archive
    .tif	        image/tiff
    .301	        application/x-301
    .906	        application/x-906
    .a11	        application/x-a11
    .ai	            application/postscript
    .aifc	        audio/aiff
    .anv	        application/x-anv
    .asf	        video/x-ms-asf
    .asx	        video/x-ms-asf
    .avi	        video/avi
    .biz	        text/xml
    .bot	        application/x-bot
    .c90	        application/x-c90
    .cat	        application/vnd.ms-pki.seccat
    .cdr	        application/x-cdr
    .cer	        application/x-x509-ca-cert
    .cgm	        application/x-cgm
    .class	        java/*
    .cmp	        application/x-cmp
    .cot	        application/x-cot
    .crt	        application/x-x509-ca-cert
    .css	        text/css
    .dbf	        application/x-dbf
    .dbx	        application/x-dbx
    .dcx	        application/x-dcx
    .dgn	        application/x-dgn
    .dll	        application/x-msdownload
    .dot	        application/msword
    .dtd	        text/xml
    .dwf	        application/x-dwf
    .dxb	        application/x-dxb
    .edn	        application/vnd.adobe.edn
    .eml	        message/rfc822
    .epi	        application/x-epi
    .eps	        application/postscript
    .exe	        application/x-msdownload
    .fdf	        application/vnd.fdf
    .fo	            text/xml
    .g4	            application/x-g4
    .	            application/x-
    .gl2	        application/x-gl2
    .hgl	        application/x-hgl
    .hpg	        application/x-hpgl
    .hqx	        application/mac-binhex40
    .hta	        application/hta
    .htm	        text/html
    .htt	        text/webviewhtml
    .icb	        application/x-icb
    .ico	        application/x-ico
    .ig4	        application/x-g4
    .iii	        application/x-iphone
    .ins	        application/x-internet-signup
    .IVF	        video/x-ivf
    .jfif	        image/jpeg
    .jpe	        application/x-jpe
    .jpg	        image/jpeg
    .js	            application/x-javascript
    .la1	        audio/x-liquid-file
    .latex	        application/x-latex
    .lbm	        application/x-lbm
    .ls	            application/x-javascript
    .m1v	        video/x-mpeg
    .m3u	        audio/mpegurl
    .mac	        application/x-mac
    .math	        text/xml
    .mdb	        application/x-mdb
    .mht	        message/rfc822
    .mi	            application/x-mi
    .midi	        audio/mid
    .mml	        text/xml
    .mns	        audio/x-musicnet-stream
    .movie	        video/x-sgi-movie
    .mp2	        audio/mp2
    .mp3	        audio/mp3
    .mpa	        video/x-mpg
    .mpe	        video/x-mpeg
    .mpg	        video/mpg
    .mpp	        application/vnd.ms-project
    .mpt	        application/vnd.ms-project
    .mpv2	        video/mpeg
    .mpx	        application/vnd.ms-project
    .mxp	        application/x-mmxp
    .nrf	        application/x-nrf
    .odc	        text/x-ms-odc
    .p10	        application/pkcs10
    .p7b	        application/x-pkcs7-certificates
    .p7m	        application/pkcs7-mime
    .p7s	        application/pkcs7-signature
    .pci	        application/x-pci
    .pcx	        application/x-pcx
    .pdf	        application/pdf
    .pfx	        application/x-pkcs12
    .pic	        application/x-pic
    .pl	            application/x-perl
    .pls	        audio/scpls
    .png	        image/png
    .pot	        application/vnd.ms-powerpoint
    .ppm	        application/x-ppm
    .ppt	        application/vnd.ms-powerpoint
    .pr	            application/x-pr
    .prn	        application/x-prn
    .ps	            application/x-ps
    .ptn	        application/x-ptn
    .r3t	        text/vnd.rn-realtext3d
    .ram	        audio/x-pn-realaudio
    .rat	        application/rat-file
    .rec	        application/vnd.rn-recording
    .rgb	        application/x-rgb
    .rjt	        application/vnd.rn-realsystem-rjt
    .rle	        application/x-rle
    .rmf	        application/vnd.adobe.rmf
    .rmj	        application/vnd.rn-realsystem-rmj
    .rmp	        application/vnd.rn-rn_music_package
    .rmvb	        application/vnd.rn-realmedia-vbr
    .rnx	        application/vnd.rn-realplayer
    .rpm	        audio/x-pn-realaudio-plugin
    .rt	            text/vnd.rn-realtext
    .rtf	        application/x-rtf
    .sam	        application/x-sam
    .sdp	        application/sdp
    .sit	        application/x-stuffit
    .sld	        application/x-sld
    .smi	        application/smil
    .smk	        application/x-smk
    .sol	        text/plain
    .spc	        application/x-pkcs7-certificates
    .spp	        text/xml
    .sst	        application/vnd.ms-pki.certstore
    .stm	        text/html
    .svg	        text/xml
    .tdf	        application/x-tdf
    .tga	        application/x-tga
    .tif	        application/x-tif
    .tld	        text/xml
    .torrent	    application/x-bittorrent
    .txt	        text/plain
    .uls	        text/iuls
    .vda	        application/x-vda
    .vml	        text/xml
    .vsd	        application/vnd.visio
    .vss	        application/vnd.visio
    .vst	        application/x-vst
    .vsx	        application/vnd.visio
    .vxml	        text/xml
    .wax	        audio/x-ms-wax
    .wb2	        application/x-wb2
    .wbmp	        image/vnd.wap.wbmp
    .wk3	        application/x-wk3
    .wkq	        application/x-wkq
    .wm	            video/x-ms-wm
    .wmd	        application/x-ms-wmd
    .wml	        text/vnd.wap.wml
    .wmx	        video/x-ms-wmx
    .wp6	        application/x-wp6
    .wpg	        application/x-wpg
    .wq1	        application/x-wq1
    .wri	        application/x-wri
    .ws	            application/x-ws
    .wsc	        text/scriptlet
    .wvx	        video/x-ms-wvx
    .xdr	        text/xml
    .xfdf	        application/vnd.adobe.xfdf
    .xls	        application/vnd.ms-excel
    .xlw	        application/x-xlw
    .xpl	        audio/scpls
    .xql	        text/xml
    .xsd	        text/xml
    .xslt	        text/xml
    .x_b	        application/x-x_b
    .sisx	        application/vnd.symbian.install
    .ipa	        application/vnd.iphone
    .xap	        application/x-silverlight-app
####################################################################
We use integer to represent type and subtype. The correspondence is as follows:
    type        number    subtype                       number
    application 0
    |-------------------->fractals                      0
    |-------------------->futuresplash                  1
    |-------------------->hta                           2
    |-------------------->mac-binhex40                  3
    |-------------------->msaccess                      4
    |-------------------->msword                        5
    |-------------------->octet-stream                  6
    |-------------------->pdf                           7
    |-------------------->pics-rules                    8
    |-------------------->pkcs10                        9
    |-------------------->pkcs7-mime                    10
    |-------------------->pkcs7-signature               11
    |-------------------->pkix-crl                      12
    |-------------------->postscript                    13
    |-------------------->rat-file                      14
    |-------------------->sdp                           15
    |-------------------->smil                          16
    |-------------------->streamingmedia                17
    |-------------------->vnd.adobe.edn                 18
    |-------------------->vnd.adobe.pdx                 19
    |-------------------->vnd.adobe.rmf                 20
    |-------------------->vnd.adobe.workflow            21
    |-------------------->vnd.adobe.xdp                 22
    |-------------------->vnd.adobe.xfd                 23
    |-------------------->vnd.android.package-archive   24
    |-------------------->vnd.fdf                       25
    |-------------------->vnd.iphone                    26
    |-------------------->vnd.ms-excel                  27
    |-------------------->vnd.ms-pki.certstore          28
    |-------------------->vnd.ms-pki.pko                29
    |-------------------->vnd.ms-pki.seccat             30
    |-------------------->vnd.ms-pki.stl                31
    |-------------------->vnd.ms-powerpoint             32
    |-------------------->vnd.ms-project                33
    |-------------------->vnd.ms-wpl                    34
    |-------------------->vnd.rn-realmedia              35
    |-------------------->vnd.rn-realmedia-secure       36
    |-------------------->vnd.rn-realmedia-vbr          37
    |-------------------->vnd.rn-realplayer             38
    |-------------------->vnd.rn-realsystem-rjs         39
    |-------------------->vnd.rn-realsystem-rjt         40
    |-------------------->vnd.rn-recording              41
    |-------------------->vnd.rn-rn_music_package       42
    |-------------------->vnd.rn-rsml                   43
    |-------------------->vnd.symbian.install           44
    |-------------------->vnd.visio                     45
    |-------------------->x-                            46
    |-------------------->x-C74:C222001                 47
    |-------------------->x-301                         48
    |-------------------->x-906                         49
    |-------------------->x-a11                         50
    |-------------------->x-anv                         51
    |-------------------->x-bittorrent                  52
    |-------------------->x-bmp                         53
    |-------------------->x-bot                         54
    |-------------------->x-c4t                         55
    |-------------------->x-c90                         56
    |-------------------->x-cals                        57
    |-------------------->x-cdr                         58
    |-------------------->x-cel                         59
    |-------------------->x-cgm                         60
    |-------------------->x-cit                         61
    |-------------------->x-cmp                         62
    |-------------------->x-cmx                         63
    |-------------------->x-cot                         64
    |-------------------->x-csi                         65
    |-------------------->x-cut                         66
    |-------------------->x-dbf                         67
    |-------------------->x-dbm                         68
    |-------------------->x-dbx                         69
    |-------------------->x-dcx                         70
    |-------------------->x-dgn                         71
    |-------------------->x-dib                         72
    |-------------------->x-drw                         73
    |-------------------->x-dwf                         74
    |-------------------->x-dwg                         75
    |-------------------->x-dxb                         76
    |-------------------->x-dxf                         77
    |-------------------->x-ebx                         78
    |-------------------->x-emf                         79
    |-------------------->x-epi                         80
    |-------------------->x-frm                         81
    |-------------------->x-g4                          82
    |-------------------->x-gbr                         83
    |-------------------->x-gl2                         84
    |-------------------->x-gp4                         85
    |-------------------->x-hgl                         86
    |-------------------->x-hmr                         87
    |-------------------->x-hpgl                        88
    |-------------------->x-hpl                         89
    |-------------------->x-hrf                         90
    |-------------------->x-icb                         91
    |-------------------->x-ico                         92
    |-------------------->x-icq                         93
    |-------------------->x-iff                         94
    |-------------------->x-igs                         95
    |-------------------->x-img                         96
    |-------------------->x-internet-signup             97
    |-------------------->x-iphone                      98
    |-------------------->x-javascript                  99
    |-------------------->x-jpe                         100
    |-------------------->x-jpg                         101
    |-------------------->x-laplayer-reg                102
    |-------------------->x-latex                       103
    |-------------------->x-lbm                         104
    |-------------------->x-ltr                         105
    |-------------------->x-mac                         106
    |-------------------->x-mdb                         107
    |-------------------->x-mi                          108
    |-------------------->x-mil                         109
    |-------------------->x-mmxp                        110
    |-------------------->x-msdownload                  111
    |-------------------->x-ms-wmd                      112
    |-------------------->x-ms-wmz                      113
    |-------------------->x-netcdf                      114
    |-------------------->x-nrf                         115
    |-------------------->x-out                         116
    |-------------------->x-pc5                         117
    |-------------------->x-pci                         118
    |-------------------->x-pcl                         119
    |-------------------->x-pcx                         120
    |-------------------->x-perl                        121
    |-------------------->x-pgl                         122
    |-------------------->x-pic                         123
    |-------------------->x-pkcs12                      124
    |-------------------->x-pkcs7-certificates          125
    |-------------------->x-pkcs7-certreqresp           126
    |-------------------->x-plt                         127
    |-------------------->x-png                         128
    |-------------------->x-ppm                         129
    |-------------------->x-ppt                         130
    |-------------------->x-pr                          131
    |-------------------->x-prn                         132
    |-------------------->x-prt                         133
    |-------------------->x-ps                          134
    |-------------------->x-ptn                         135
    |-------------------->x-ras                         136
    |-------------------->x-red                         137
    |-------------------->x-rgb                         138
    |-------------------->x-rlc                         139
    |-------------------->x-rle                         140
    |-------------------->x-rtf                         141
    |-------------------->x-sam                         142
    |-------------------->x-sat                         143
    |-------------------->x-sdw                         144
    |-------------------->x-shockwave-flash             145
    |-------------------->x-silverlight-app             146
    |-------------------->x-slb                         147
    |-------------------->x-sld                         148
    |-------------------->x-smk                         149
    |-------------------->x-stuffit                     150
    |-------------------->x-sty                         151
    |-------------------->x-tdf                         152
    |-------------------->x-tg4                         153
    |-------------------->x-tga                         154
    |-------------------->x-tif                         155
    |-------------------->x-troff-man                   156
    |-------------------->x-vda                         157
    |-------------------->x-vpeg005                     158
    |-------------------->x-vsd                         159
    |-------------------->x-vst                         160
    |-------------------->x-wb1                         161
    |-------------------->x-wb2                         162
    |-------------------->x-wb3                         163
    |-------------------->x-wk3                         164
    |-------------------->x-wk4                         165
    |-------------------->x-wkq                         166
    |-------------------->x-wks                         167
    |-------------------->x-wmf                         168
    |-------------------->x-wp6                         169
    |-------------------->x-wpd                         170
    |-------------------->x-wpg                         171
    |-------------------->x-wq1                         172
    |-------------------->x-wr1                         173
    |-------------------->x-wri                         174
    |-------------------->x-wrk                         175
    |-------------------->x-ws                          176
    |-------------------->x-x_b                         177
    |-------------------->x-x_t                         178
    |-------------------->x-x509-ca-cert                179
    |-------------------->x-xls                         180
    |-------------------->x-xlw                         181
    |-------------------->x-xwd                         182
    audio       1
    |-------------------->aiff                          0
    |-------------------->basic                         1
    |-------------------->mid                           2
    |-------------------->mp1                           3
    |-------------------->mp2                           4
    |-------------------->mp3                           5
    |-------------------->mpegurl                       6
    |-------------------->rn-mpeg                       7
    |-------------------->scpls                         8
    |-------------------->vnd.rn-realaudio              9
    |-------------------->wav                           10
    |-------------------->x-la-lms                      11
    |-------------------->x-liquid-file                 12
    |-------------------->x-liquid-secure               13
    |-------------------->x-mei-aac                     14
    |-------------------->x-ms-wax                      15
    |-------------------->x-ms-wma                      16
    |-------------------->x-musicnet-download           17
    |-------------------->x-musicnet-stream             18
    |-------------------->x-pn-realaudio                19
    |-------------------->x-pn-realaudio-plugin         20
    drawing     2
    |-------------------->907                           0
    |-------------------->x-slk                         1
    |-------------------->x-top                         2
    image       3
    |-------------------->fax                           0
    |-------------------->gif                           1
    |-------------------->jpeg                          2
    |-------------------->pnetvue                       3
    |-------------------->png                           4
    |-------------------->tiff                          5
    |-------------------->vnd.rn-realpix                6
    |-------------------->vnd.wap.wbmp                  7
    |-------------------->x-icon                        8
    java        4
    |-------------------->*                             0
    message     5
    |-------------------->rfc822                        0
    Model       6
    |-------------------->vnd.dwf                       0
    text        7
    |-------------------->asa                           0
    |-------------------->asp                           1
    |-------------------->css                           2
    |-------------------->h323                          3
    |-------------------->html                          4
    |-------------------->iuls                          5
    |-------------------->plain                         6
    |-------------------->scriptlet                     7
    |-------------------->vnd.rn-realtext               8
    |-------------------->vnd.rn-realtext3d             9
    |-------------------->vnd.wap.wml                   10
    |-------------------->webviewhtml                   11
    |-------------------->x-component                   12
    |-------------------->xml                           13
    |-------------------->x-ms-odc                      14
    |-------------------->x-vcard                       15
    video       8
    |-------------------->avi                           0
    |-------------------->mpeg                          1
    |-------------------->mpeg4                         2
    |-------------------->mpg                           3
    |-------------------->vnd.rn-realvideo              4
    |-------------------->x-ivf                         5
    |-------------------->x-mpeg                        6
    |-------------------->x-mpg                         7
    |-------------------->x-ms-asf                      8
    |-------------------->x-ms-wm                       9
    |-------------------->x-ms-wmv                      10
    |-------------------->x-ms-wmx                      11
    |-------------------->x-ms-wvx                      12
    |-------------------->x-sgi-movie                   13
"""